### ISSUE TITLE
posture tracker application example

### ISSUE THREAD

**Issue by TobiasRoeddiger** [OpenEarable/app#1]

**Comment by DennisMoschina** [comment]
"I created a quick mockup sketch for an idea on how the head could be rendered. The range of motion in this model is limited, as it is not a real 3D model, but I believe it should be suitable for real-world applications.

![IMG_94E9EC449BE2-1](https://github.com/OpenEarable/app/assets/45356478/62942fb4-3096-4031-b959-840b5e7813f5)

**Comment by TobiasRoeddiger** [comment]
the sound ore liberty buds have a really nice ui for this i‘ll send it through when i‘m back

**Comment by DennisMoschina** [comment]
I found this online. I'll implement something similar to this

![Bildschirmfoto 2023-09-09 um 13 32 33](https://github.com/OpenEarable/app/assets/45356478/7a0c2fb3-e86a-4737-a658-a74c0d4057da)

**Comment by TobiasRoeddiger** [comment]
exactly, that‘s what i meant

**Comment by TobiasRoeddiger** [comment]
very nice, does it work with OpenEarable?
