### ISSUE TITLE
Change icons on app bar for control and sensor

### ISSUE THREAD

**Issue by TobiasRoeddiger** [OpenEarable/app#19]
Not sure what to do with the controls icon, but for the sensor it would be nice if we had something like a line that looks like sensor data

**Comment by ilteen** [comment]
possible icons?

for sensors
<img width="117" alt="Screenshot 2023-11-19 at 19 27 33" src="https://github.com/OpenEarable/app/assets/35779536/232c537e-5e60-4271-ae65-febcbaae932e">
<img width="104" alt="Screenshot 2023-11-19 at 19 27 49" src="https://github.com/OpenEarable/app/assets/35779536/31b7edfc-cc36-4586-a127-7b2d4eb8f5e0">
<img width="116" alt="Screenshot 2023-11-19 at 19 28 07" src="https://github.com/OpenEarable/app/assets/35779536/05fe79d3-dd31-478f-981a-5da842e6b08a">
<img width="128" alt="Screenshot 2023-11-19 at 19 33 07" src="https://github.com/OpenEarable/app/assets/35779536/7b5e9894-2ce9-404c-b8a8-d54ebda2d369">
<img width="101" alt="Screenshot 2023-11-19 at 19 33 23" src="https://github.com/OpenEarable/app/assets/35779536/0d4802dd-f3fb-447a-a0ab-d60ccd9b1c15">

for controls
<img width="102" alt="Screenshot 2023-11-19 at 19 33 33" src="https://github.com/OpenEarable/app/assets/35779536/7f097b21-6423-430b-94f2-770dc12bd702">
<img width="114" alt="Screenshot 2023-11-19 at 19 34 29" src="https://github.com/OpenEarable/app/assets/35779536/87bdf619-c0dd-4d44-b52a-36f0947abf4e">
<img width="127" alt="Screenshot 2023-11-19 at 19 31 51" src="https://github.com/OpenEarable/app/assets/35779536/9656194a-c8e5-4d20-9ea3-69e14311e7c4">
<img width="97" alt="Screenshot 2023-11-19 at 19 32 07" src="https://github.com/OpenEarable/app/assets/35779536/51caf9b0-c576-4f93-9c86-7764433a89e6">
