### ISSUE TITLE
Acceleration data in m/s^2, but shows g in app

### ISSUE THREAD

**Issue by probstlukas** [OpenEarable/app#30]
I am working on an app as part of the lecture MoCIoT, where I am using acceleration data of the device. When I navigate to Sensor Data --> Accel., I noticed that when I hold the device upright, X and Y are 0, but Z is 9.81. It shows the unit g in brackets behind the axes at the bottom. However, since Z is 9.81 when I hold the device steady and upright, this implies that the data which is shown here is actually in m/s^2. If it would be in g, Z should be ±1 g, when the device is in a vertical position such that one of its axes aligns with gravity. Or am I mistaken?

<img src="https://github.com/OpenEarable/app/assets/35579454/e2a15be1-539f-41cc-a83d-af78ca20bec8" width=25% height=25%>

**Comment by o-bagge** [comment]
Fixed. All units are now hard coded in app and not read from earable anymore
