### ISSUE TITLE
add option for automatic reconnect on the connection page

### ISSUE THREAD

**Issue by TobiasRoeddiger** [OpenEarable/app#57]
would be nice to have a toggle switch on the connectin page that can be used to enable automatic reconnecting

questions
- [ ] how should the recorder handle reconnects?
- [ ] can we make this stateless?

---
reported by @kkai on iOS

**Comment by o-bagge** [comment]
Woud maybe make sense to stop the recording when the earable disconnects and save the recorded data up to that point.

What do you mean by stateless @TobiasRoeddiger?

**Comment by TobiasRoeddiger** [comment]
yeah that makes sense, stop the recording and save it
